---
dist: trusty
language: ruby
cache: bundler
before_install:
  - if [ $BUNDLER_VERSION ]; then
      gem install -v $BUNDLER_VERSION bundler --no-rdoc --no-ri;
    fi
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
  - rvm: '2.4'
    env: PUPPET_GEM_VERSION='~> 5.0'
  - rvm: '2.3'
    env: PUPPET_GEM_VERSION='~> 5.0'
  - rvm: '2.1'
    env: PUPPET_GEM_VERSION='~> 5.0'
  - rvm: '2.4'
    env: PUPPET_GEM_VERSION='~> 4.0'
  - rvm: '2.3'
    env: PUPPET_GEM_VERSION='~> 4.0'
  - rvm: '2.1'
    env: PUPPET_GEM_VERSION='~> 4.0'
  - rvm: '2.1'
    env: PUPPET_GEM_VERSION='~> 3.0'
  - rvm: '2.0'
    env: PUPPET_GEM_VERSION='~> 3.0'
  - rvm: '1.9'
    env: PUPPET_GEM_VERSION='~> 3.0'
notifications:
  email: false
